using System.Net;
using HtmlAgilityPack;
using Microsoft.AspNetCore.WebUtilities;

class AnimeResult
{
    public string Name { get; set; } = "";
    public string Url { get; set; } = "";
}

public class Program
{
    private static HttpClient sharedClient = new() { BaseAddress = new Uri("https://hianime.ms/") };

    private static async Task<HtmlDocument> GetHtml(string path)
    {
        using HttpResponseMessage response = await sharedClient.GetAsync(path);
        response.EnsureSuccessStatusCode();
        string content = await response.Content.ReadAsStringAsync();

        HtmlDocument doc = new();
        doc.LoadHtml(content);

        return doc;
    }

    private static async Task<List<AnimeResult>> MakeSearchQuery(string title)
    {
        var queryParams = new Dictionary<string, string?> { { "q", title } };

        string fullUrl = QueryHelpers.AddQueryString(
            $"{sharedClient.BaseAddress}search",
            queryParams
        );

        HtmlDocument doc = await GetHtml(fullUrl);
        var itemList = doc.DocumentNode.SelectNodes("//div[@class='film-detail']"); // Returns an enumerable

        // Parse html
        List<AnimeResult> animeList = new();
        if (itemList != null)
        {
            foreach (var item in itemList)
            {
                // NOTE: MUST add the "." prefix, otherwise the function will search the entire document, rather than relative the current node
                var link = item.SelectSingleNode(@".//a[@class='dynamic-name']");

                if (link != null)
                {
                    animeList.Add(
                        new AnimeResult
                        {
                            Name = link.InnerText.Trim(),
                            Url = link.GetAttributeValue("href", ""),
                        }
                    );
                }
            }
        }

        return animeList;
    }

    private static async Task<List<AnimeResult>> GetEpisodeList(string path)
    {
        // Because of the way the website is structured, we have to get to first episode just to see the episode list...
        HtmlDocument doc = await GetHtml(path);

        var item = doc.DocumentNode.SelectSingleNode(
            @"//a[@class='btn btn-radius btn-primary btn-play']"
        );

        List<AnimeResult> epList = new();

        if (item != null)
        {
            var link = item.GetAttributeValue("href", "");
            doc = await GetHtml(link);

            // Actually scrape episode list

            // Parsing rule generated by ChatGPT
            var itemList = doc.DocumentNode.SelectNodes(
                "//a[contains(concat(' ', normalize-space(@class), ' '), ' ws-ep ')]"
            );

            // Parse html
            if (itemList != null)
            {
                for (int i = 0; i < itemList.Count; i++)
                {
                    item = itemList[i];

                    var title = WebUtility.HtmlDecode(
                        item.SelectSingleNode(@".//span[@class='ws-ep__title']").InnerText.Trim()
                    );

                    var url = item.GetAttributeValue("href", "");

                    epList.Add(new AnimeResult { Name = title, Url = url });
                }
            }
        }

        return epList;
    }

    private static async Task PlayEpisode(string path)
    {
        var doc = await GetHtml(path);

        var item = doc.DocumentNode.SelectSingleNode(@"//iframe");
        // var item = doc.DocumentNode.SelectSingleNode(@"//iframe[@label='Video player']");

        Console.WriteLine(item.OuterHtml);

        if (item != null)
        {
            var link = item.GetAttributeValue("src", "");
            Console.WriteLine(@link);
        }
        else
            Console.WriteLine("Could not find link");
    }

    public static async Task Main(string[] args)
    {
        List<AnimeResult> animeList = new();
        bool valid = false;

        while (animeList.Count == 0)
        {
            string? title = "";

            while (!valid)
            {
                Console.Write("Please enter a title: ");
                title = Console.ReadLine()?.Trim();

                if (title == "")
                    Console.WriteLine("Invalid title. Please try again.");
                else
                    valid = true;
            }

            animeList = await MakeSearchQuery(title!);

            if (animeList.Count == 0)
            {
                Console.WriteLine("No results found. Searching again...");
                valid = false;
            }
        }

        for (int i = 0; i < animeList.Count; i++)
        {
            var anime = animeList[i];
            Console.WriteLine($"{i}) {anime.Name}");
        }

        Console.WriteLine("Select an anime: ");
        int index = -100;
        valid = false;
        while (!valid)
        {
            string? input = Console.ReadLine()?.Trim();
            int.TryParse(input, out index);

            if (index < 0 || index > animeList.Count - 1)
            {
                Console.WriteLine("Invalid input. Please try again.");
            }
            else
                valid = true;
        }

        var epList = await GetEpisodeList(animeList[index].Url);
        foreach (var ep in epList)
        {
            Console.WriteLine($"{ep.Name}");
        }

        await PlayEpisode(epList[0].Url);
    }
}
